# Site parameters
url: https://benjamin.thouret.com
name: Benjamin Thouret
email: ben@thouret.com
location: "Montreal, QC"
tagline: "aligning business & technology"
head_tagline: "Senior Software Architect dedicated to helping great companies build successful web applications"
ga: UA-35548726-1           #Google Analytics ID

# Jekyll configuration
rouge: true
