# Site parameters
url: http://benjamin.thouret.com
name: Benjamin Thouret
email: ben@thouret.com
phone: "+1 514-316-7604"
location: "Montreal, QC"
tagline: "aligning business & technology"
ga: UA-35548726-1           #Google Analytics ID

# Jekyll configuration
pygments: true
