# Site parameters
url: http://benjamin.thouret.com
name: Benjamin Thouret
tagline: "aligning business & technology"
ga: UA-35548726-1           #Google Analytics ID

# Jekyll configuration
pygments: true
